version: '3.0'
services:
  procol-workflows:
    container_name: procol-workflows
    restart: unless-stopped
    image: ${AP_DOCKER_IMAGE}
    platform: linux/arm64
    environment:
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
    ports:
      - ${AP_DOCKER_IMAGE_PORT}
    depends_on:
      - redis
    env_file: .env
    networks:
      - procol-workflows
  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - 'redis_data:/data'
    networks:
      - procol-workflows
volumes:
  redis_data:
networks:
  procol-workflows: